#ifndef _SSRN_CONFIG_H
#define _SSRN_CONFIG_H

#define SSRN_USE_TIMERS
#define SSRN_NUM_TIMERS 5

#define SSRN_NODE_TYPE "AM2302-V1"
#define SSRN_NODE_ID   0x01

#define SSRN_DEFAULT_BAUD_RATE SSRN_BAUD_1200

#define SSRN_RX_QUEUE_LEN 2
#define SSRN_IN_QUEUE_LEN 2
#define SSRN_TX_QUEUE_LEN 2

#endif // #ifndef _SSRN_CONFIG_H
